services:
  - type: web
    name: chocoloco-mvp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ODOO_URL
        sync: false
      - key: ODOO_DB
        sync: false
      - key: ODOO_USERNAME
        sync: false
      - key: ODOO_PASSWORD
        sync: false
